FROM node:22-alpine
WORKDIR /work/frontend
RUN sed -i 's|https://dl-cdn.alpinelinux.org|https://mirrors.tuna.tsinghua.edu.cn|g' /etc/apk/repositories \
    && apk add --no-cache chromium nss freetype harfbuzz ca-certificates font-freefont
ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
ENV PLAYWRIGHT_EXECUTABLE_PATH=/usr/bin/chromium-browser
COPY frontend/package*.json ./
RUN npm install
COPY frontend ./
CMD ["npm","run","test:e2e"]
