<script setup lang="ts">
import {onMounted,ref} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api} from '../api'
import {ArrowLeft,Database,ShieldCheck} from 'lucide-vue-next'
const route=useRoute(),router=useRouter(),item=ref<any>(null),loading=ref(true)
onMounted(async()=>{try{item.value=(await api.get(`/data-center/versions/${route.params.id}`)).data}finally{loading.value=false}})
</script>
<template><section class="workflow"><div class="crumb"><button @click="router.push('/data-center')"><ArrowLeft :size="15"/>返回数据中心</button><span>数据质量详情</span></div><div v-if="loading" class="panel empty">正在读取数据版本…</div><template v-else-if="item"><article class="model-hero"><div class="feature-icon"><Database :size="24"/></div><div><span class="eyebrow dark">{{item.layer}}</span><h2>{{item.specification?.name||'行情研究数据'}}</h2><p>{{item.specification?.start_date}} 至 {{item.specification?.end_date}}</p></div><i class="status" :class="item.status">{{item.status}}</i></article><div class="detail-grid"><article class="panel"><div class="panel-head"><div><h3>完整性与覆盖</h3><p>标准化质量门禁结果</p></div><ShieldCheck :size="18"/></div><dl class="detail-list"><div><dt>记录行数</dt><dd>{{item.row_count}}</dd></div><div><dt>标的数量</dt><dd>{{item.quality_report?.symbol_count??'—'}}</dd></div><div><dt>日期范围</dt><dd>{{item.quality_report?.date_min||'—'}} → {{item.quality_report?.date_max||'—'}}</dd></div><div><dt>日历缺失</dt><dd>{{item.quality_report?.missing_calendar_rows??0}}</dd></div><div><dt>停牌记录</dt><dd>{{item.quality_report?.suspended_rows??0}}</dd></div><div><dt>质量警告</dt><dd>{{item.quality_report?.warnings?.join('；')||'无'}}</dd></div></dl></article><article class="panel"><div class="panel-head"><div><h3>版本与血缘</h3><p>定位原始数据和转换规则</p></div></div><dl class="detail-list"><div><dt>内容 SHA256</dt><dd><code>{{item.content_sha256}}</code></dd></div><div><dt>父版本</dt><dd><code>{{item.parent_id||'—'}}</code></dd></div><div><dt>任务</dt><dd><code>{{item.job_id||'—'}}</code></dd></div><div><dt>产物地址</dt><dd><code>{{item.artifact_uri}}</code></dd></div></dl><div class="artifact"><code>{{JSON.stringify(item.lineage,null,2)}}</code></div></article></div><article class="panel"><div class="panel-head"><div><h3>同步规格</h3><p>创建该版本时的不可变输入</p></div></div><div class="artifact"><code>{{JSON.stringify(item.specification,null,2)}}</code></div></article></template></section></template>
