<script setup lang="ts">
import {computed,onMounted,ref} from 'vue'
import {api} from '../api'
import {Ban,Landmark,Play,RefreshCw,ShieldAlert,WalletCards} from 'lucide-vue-next'

const accounts=ref<any[]>([]),selected=ref(''),data=ref<any>(null),loading=ref(false),busy=ref(false),error=ref(''),notice=ref('')
const models=ref<any[]>([]),automationSchedules=ref<any[]>([]),automationRuns=ref<any[]>([])
const brokerConnections=ref<any[]>([]),readinessEvaluations=ref<any[]>([]),brokerPreview=ref<any[]>([])
const accountForm=ref({name:'A股策略模拟账户',initial_cash:1000000,max_order_value:100000,max_position_ratio:0.3})
const order=ref({symbol:'600000',side:'buy',quantity:100,snapshot_price:10,trade_date:new Date().toISOString().slice(0,10),source:'manual_replay'})
const automationForm=ref({name:'每日模型调仓',algorithm:'logistic_regression',interval_minutes:1440,top_n:5,probability_threshold:0.55,gross_exposure:0.95,enabled:false})
const brokerForm=ref({name:'券商接口准备区',provider:'generic',environment:'sandbox',credential_secret_ref:'env:QUANT_BROKER_GENERIC_TOKEN'})
const account=computed(()=>data.value?.account)
const productionModels=computed(()=>models.value.filter(item=>item.stage==='production'))

async function loadAccounts(){
  const [accountResponse,modelResponse,scheduleResponse,runResponse,connectionResponse,evaluationResponse]=await Promise.all([
    api.get('/paper/accounts'),api.get('/models'),api.get('/paper-automation-schedules'),api.get('/paper-automation-runs'),api.get('/broker-safety/connections'),api.get('/broker-safety/evaluations'),
  ])
  accounts.value=accountResponse.data;models.value=modelResponse.data;automationSchedules.value=scheduleResponse.data;automationRuns.value=runResponse.data
  brokerConnections.value=connectionResponse.data;readinessEvaluations.value=evaluationResponse.data
  if(!selected.value&&accounts.value.length)selected.value=accounts.value[0].id
  if(productionModels.value.length&&!productionModels.value.some(item=>item.algorithm===automationForm.value.algorithm))automationForm.value.algorithm=productionModels.value[0].algorithm
  if(selected.value)await loadSnapshot()
}
async function loadSnapshot(){loading.value=true;try{data.value=(await api.get(`/paper/accounts/${selected.value}`)).data}finally{loading.value=false}}
async function createAccount(){error.value='';try{const created=(await api.post('/paper/accounts',accountForm.value)).data;selected.value=created.id;await loadAccounts();notice.value='模拟账户已创建'}catch(e:any){error.value=e.response?.data?.detail||e.message}}
async function submitOrder(){error.value='';notice.value='';try{const result=(await api.post(`/paper/accounts/${selected.value}/orders`,order.value)).data;notice.value=result.status==='filled'?'模拟成交完成':`订单被风控拒绝：${result.message}`;await loadSnapshot()}catch(e:any){error.value=e.response?.data?.detail||e.message}}
async function createAutomation(){busy.value=true;error.value='';try{await api.post('/paper-automation-schedules',{...automationForm.value,account_id:selected.value});notice.value='自动链路已创建，默认暂停；启用前可先手动运行检查提案';await loadAccounts()}catch(e:any){error.value=e.response?.data?.detail||e.message}finally{busy.value=false}}
async function runAutomation(item:any){busy.value=true;error.value='';try{await api.post(`/paper-automation-schedules/${item.id}/run`);notice.value='任务已入队；完成后订单会以“待复核”状态出现';await loadAccounts()}catch(e:any){error.value=e.response?.data?.detail||e.message}finally{busy.value=false}}
async function toggleAutomation(item:any){busy.value=true;try{await api.patch(`/paper-automation-schedules/${item.id}`,{enabled:!item.enabled});await loadAccounts()}catch(e:any){error.value=e.response?.data?.detail||e.message}finally{busy.value=false}}
async function createBrokerBoundary(){busy.value=true;error.value='';try{await api.post('/broker-safety/connections',{...brokerForm.value,paper_account_id:selected.value});notice.value='已登记禁用状态的券商边界；只保存密钥引用，不会连接或发单';await loadAccounts()}catch(e:any){error.value=e.response?.data?.detail||e.message}finally{busy.value=false}}
async function evaluateBroker(item:any){busy.value=true;try{await api.post(`/broker-safety/connections/${item.id}/evaluate`);await loadAccounts()}catch(e:any){error.value=e.response?.data?.detail||e.message}finally{busy.value=false}}
async function previewBroker(item:any){brokerPreview.value=(await api.get(`/broker-safety/connections/${item.id}/preview`)).data;notice.value=`dry-run 预览 ${brokerPreview.value.length} 笔，传输状态全部为 false`}
function latestEvaluation(connectionId:string){return readinessEvaluations.value.find(item=>item.connection_id===connectionId)}
async function settle(){error.value='';try{data.value=(await api.post(`/paper/accounts/${selected.value}/settle`,{trade_date:order.value.trade_date})).data;notice.value='交易日结算完成，历史买入持仓已更新为可卖'}catch(e:any){error.value=e.response?.data?.detail||e.message}}
async function freeze(){if(!confirm('确认冻结该模拟账户？冻结后不能继续下单。'))return;await api.post(`/paper/accounts/${selected.value}/freeze`);await loadSnapshot()}
onMounted(()=>loadAccounts().catch(e=>error.value=e.response?.data?.detail||e.message))
</script>

<template>
  <section>
    <div class="page-intro"><div><h2>模拟交易台</h2><p>模型信号 → 目标仓位 → 待复核订单；完全隔离，不连接券商</p></div><div class="paper-badge"><ShieldAlert :size="15"/>PAPER ONLY</div></div>
    <p v-if="error" class="error-box">{{error}}</p><p v-if="notice" class="notice-box">{{notice}}</p>
    <article v-if="!accounts.length" class="panel empty-account"><WalletCards :size="40"/><h3>创建第一个模拟账户</h3><p>使用虚拟资金验证策略、交易规则和风险限制。</p><div class="form-grid"><div class="field"><label>账户名称</label><input v-model="accountForm.name"/></div><div class="field"><label>初始虚拟资金</label><input v-model.number="accountForm.initial_cash" type="number"/></div><div class="field"><label>单笔金额上限</label><input v-model.number="accountForm.max_order_value" type="number"/></div><div class="field"><label>单票仓位上限</label><input v-model.number="accountForm.max_position_ratio" type="number" step="0.05"/></div></div><button class="primary" @click="createAccount">创建模拟账户</button></article>
    <template v-else>
      <div class="paper-toolbar"><select v-model="selected" @change="loadSnapshot"><option v-for="item in accounts" :key="item.id" :value="item.id">{{item.name}}</option></select><button class="secondary" @click="loadAccounts"><RefreshCw :size="15" :class="{spin:loading}"/>刷新</button><button class="secondary danger-outline" @click="freeze"><Ban :size="15"/>紧急冻结</button></div>
      <div v-if="data" class="paper-metrics"><article><small>总资产</small><strong>¥{{Number(data.equity).toLocaleString()}}</strong></article><article><small>可用资金</small><strong>¥{{Number(account.cash).toLocaleString()}}</strong></article><article><small>持仓市值</small><strong>¥{{Number(data.market_value).toLocaleString()}}</strong></article><article><small>累计盈亏</small><strong :class="Number(data.total_profit)>=0?'gain':'loss'">¥{{Number(data.total_profit).toLocaleString()}}</strong></article><article><small>账户状态</small><i class="status" :class="account.status">{{account.status}}</i></article></div>
      <div class="detail-grid operations-grid">
        <article class="panel"><div class="panel-head"><div><h3>模型自动调仓</h3><p>自动使用最新兼容快照；订单只生成提案，不自动成交</p></div><ShieldAlert :size="19"/></div><div class="field"><label>计划名称</label><input v-model="automationForm.name"/></div><div class="field"><label>生产模型算法</label><select v-model="automationForm.algorithm"><option v-for="item in productionModels" :key="item.algorithm" :value="item.algorithm">{{item.name}} · {{item.algorithm}}</option></select></div><div class="form-grid"><div class="field"><label>选股数量</label><input v-model.number="automationForm.top_n" type="number" min="1" max="50"/></div><div class="field"><label>最低上涨概率</label><input v-model.number="automationForm.probability_threshold" type="number" step="0.01" min="0.5" max="0.99"/></div><div class="field"><label>总仓位上限</label><input v-model.number="automationForm.gross_exposure" type="number" step="0.05" min="0.05" max="1"/></div><div class="field"><label>运行间隔（分钟）</label><input v-model.number="automationForm.interval_minutes" type="number" min="30"/></div></div><button class="primary" :disabled="busy||!productionModels.length" @click="createAutomation">创建暂停中的计划</button></article>
        <article class="panel"><div class="panel-head"><div><h3>手工模拟下单</h3><p>用于历史回放和订单风控验证</p></div><Landmark :size="19"/></div><div class="field"><label>证券代码</label><input v-model="order.symbol" maxlength="6"/></div><div class="side-switch"><button :class="{selected:order.side==='buy'}" @click="order.side='buy'">买入</button><button :class="{selected:order.side==='sell'}" @click="order.side='sell'">卖出</button></div><div class="form-grid"><div class="field"><label>数量（整手）</label><input v-model.number="order.quantity" type="number" step="100" min="100"/></div><div class="field"><label>回放价格</label><input v-model.number="order.snapshot_price" type="number" step="0.01"/></div></div><div class="field"><label>模拟交易日</label><input v-model="order.trade_date" type="date"/></div><button class="primary" :disabled="account?.status!=='active'" @click="submitOrder">提交模拟订单</button><button class="secondary settle-button" @click="settle">推进至该交易日并结算 T+1</button></article>
      </div>
      <article class="panel"><div class="panel-head"><div><h3>自动调仓计划</h3><p>同一计划不会重复处理同一张快照</p></div></div><div class="data-table"><div class="data-row header with-action"><span>计划 / 算法</span><span>规则</span><span>状态</span><span>上次任务</span><span>操作</span></div><div v-for="item in automationSchedules" :key="item.id" class="data-row with-action"><span>{{item.name}}<small>{{item.algorithm}}</small></span><span>Top {{item.top_n}} · P≥{{item.probability_threshold}} · 仓位≤{{item.gross_exposure}}</span><span><i class="status" :class="item.enabled?'succeeded':'archived'">{{item.enabled?'enabled':'paused'}}</i></span><span><code>{{item.last_job_id?.slice(0,8)||'—'}}</code></span><span class="row-actions"><button class="text-button" :disabled="busy" @click="runAutomation(item)"><Play :size="14"/>运行</button><button class="text-button" :disabled="busy" @click="toggleAutomation(item)">{{item.enabled?'暂停':'启用'}}</button></span></div><div v-if="!automationSchedules.length" class="empty">暂无自动调仓计划。</div></div></article>
      <div v-if="data" class="paper-records"><article class="panel"><div class="panel-head"><div><h3>当前持仓</h3><p>买入当日数量不会进入可卖持仓</p></div></div><div class="mini-row mini-head"><span>代码</span><span>数量/可卖</span><span>成本</span><span>最新价</span></div><div class="mini-row" v-for="position in data.positions" :key="position.id"><b>{{position.symbol}}</b><span>{{position.quantity}} / {{position.sellable_quantity}}</span><span>{{position.average_cost}}</span><span>{{position.last_price}}</span></div><div v-if="!data.positions.length" class="empty">暂无持仓</div></article><article class="panel"><div class="panel-head"><div><h3>最近订单</h3><p>模型订单会显示 proposed，明确区分信号日和拟成交日</p></div></div><div class="mini-row order-history mini-head"><span>拟成交日</span><span>代码</span><span>方向</span><span>来源</span><span>状态</span></div><div class="mini-row order-history" v-for="item in data.orders.slice(0,12)" :key="item.id"><span>{{item.trade_date}}</span><b>{{item.symbol}}</b><span>{{item.side}} · {{item.quantity}}</span><span>{{item.source}}</span><i class="status" :class="item.status">{{item.status}}</i></div><div v-if="!data.orders.length" class="empty">暂无订单</div></article></div>
      <article v-if="automationRuns.length" class="panel"><div class="panel-head"><div><h3>自动链路审计</h3><p>模型、快照、数据版本、信号与目标仓位均永久留痕</p></div></div><div class="data-table"><div class="data-row header"><span>信号日</span><span>拟成交日</span><span>状态</span><span>订单数</span></div><div v-for="item in automationRuns.slice(0,20)" :key="item.id" class="data-row"><span>{{item.signal_date||'计算中'}}</span><span>{{item.intended_trade_date||'—'}}</span><i class="status" :class="item.status">{{item.status}}</i><span>{{item.order_ids.length}}</span></div></div></article>
      <article class="panel"><div class="panel-head"><div><h3>实盘准备门禁</h3><p>这里只评估模拟盘稳定性并生成不传输的 dry-run 预览；没有真实发单接口</p></div><ShieldAlert :size="19"/></div><div class="form-grid"><div class="field"><label>配置名称</label><input v-model="brokerForm.name"/></div><div class="field"><label>提供方标识</label><input v-model="brokerForm.provider"/></div><div class="field"><label>环境</label><select v-model="brokerForm.environment"><option value="sandbox">sandbox</option><option value="live">live（仍强制 dry-run）</option></select></div><div class="field"><label>凭据环境变量引用</label><input v-model="brokerForm.credential_secret_ref"/></div></div><button class="primary" :disabled="busy" @click="createBrokerBoundary">登记禁用的券商边界</button><div class="data-table"><div class="data-row header with-action"><span>配置 / 提供方</span><span>模式</span><span>稳定性门禁</span><span>状态</span><span>操作</span></div><div v-for="item in brokerConnections" :key="item.id" class="data-row with-action"><span>{{item.name}}<small>{{item.provider}} · {{item.environment}}</small></span><span>dry-run={{item.dry_run}}</span><span><i class="status" :class="latestEvaluation(item.id)?.eligible?'succeeded':'warning'">{{latestEvaluation(item.id)?.eligible?'eligible':'blocked / 未评估'}}</i></span><span>{{item.status}}</span><span class="row-actions"><button class="text-button" @click="evaluateBroker(item)">重新评估</button><button class="text-button" @click="previewBroker(item)">订单预览</button></span></div><div v-if="!brokerConnections.length" class="empty">尚未登记券商边界。选择真实提供方和凭据前可保持为空。</div></div></article>
    </template>
  </section>
</template>
