<script setup lang="ts">
import {computed,onMounted,ref} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api} from '../api'
import {ArrowLeft,GitBranch,Sparkles} from 'lucide-vue-next'
const route=useRoute(),router=useRouter(),item=ref<any>(null),loading=ref(true)
const features=computed(()=>Object.entries(item.value?.profile?.features||{}))
onMounted(async()=>{try{item.value=(await api.get(`/data-center/materializations/${route.params.id}`)).data}finally{loading.value=false}})
</script>
<template><section class="workflow"><div class="crumb"><button @click="router.push('/data-center')"><ArrowLeft :size="15"/>返回数据中心</button><span>特征快照详情</span></div><div v-if="loading" class="panel empty">正在读取特征快照…</div><template v-else-if="item"><article class="model-hero"><div class="feature-icon purple-bg"><Sparkles :size="24"/></div><div><span class="eyebrow dark">FEATURE SNAPSHOT</span><h2>{{item.name}}</h2><p>{{item.row_count}} 行 · {{features.length}} 个特征</p></div><i class="status" :class="item.status">{{item.status}}</i></article><article class="panel"><div class="panel-head"><div><h3>特征分布画像</h3><p>{{item.profile?.date_min}} → {{item.profile?.date_max}}</p></div></div><div class="data-table"><div class="data-row header"><span>特征</span><span>缺失率</span><span>均值 / 标准差</span><span>范围</span></div><div v-for="[name,raw] in features" :key="name" class="data-row"><code>{{name}}</code><span>{{((raw as any).missing_rate*100).toFixed(2)}}%</span><span>{{(raw as any).mean}} / {{(raw as any).std}}</span><span>{{(raw as any).min}} → {{(raw as any).max}}</span></div></div></article><div class="detail-grid"><article class="panel"><div class="panel-head"><div><h3>不可变标识</h3><p>用于数据集和漂移检查</p></div></div><dl class="detail-list"><div><dt>内容 SHA256</dt><dd><code>{{item.content_sha256}}</code></dd></div><div><dt>数据版本</dt><dd><RouterLink :to="`/data-center/versions/${item.data_version_id}`">{{item.data_version_id}}</RouterLink></dd></div><div><dt>产物地址</dt><dd><code>{{item.artifact_uri}}</code></dd></div></dl></article><article class="panel"><div class="panel-head"><div><h3>完整血缘</h3><p>数据版本、特征定义和物化管线</p></div><GitBranch :size="18"/></div><div class="artifact"><code>{{JSON.stringify(item.lineage,null,2)}}</code></div></article></div></template></section></template>
